[package]
name = "unic-langid"
description = "API for managing Unicode Language Identifiers"
version = "0.1.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["internationalization"]

[dev-dependencies]
criterion = "^0.2"

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "langid"
harness = false

[[bench]]
name = "canonicalize"
harness = false
