[package]
name = "unic-langid"
description = "API for managing Unicode Language Identifiers"
version = "0.5.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zbraniecki/unic-locale"
license = "MIT/Apache-2.0"
categories = ["internationalization"]

[dependencies]
unic-langid-impl = "0.5"
unic-langid-macros = { version = "0.5", optional = true }
[dev-dependencies]
unic-langid-macros = "0.5"

[features]
default = []

# Provide macros.
macros = ["unic-langid-macros"]
