[package]
name = "unic-locale"
description = "API for managing Unicode Locale Identifiers"
version = "0.2.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zbraniecki/unic-locale"
license = "MIT/Apache-2.0"
categories = ["internationalization"]

[dependencies]
unic-langid = "^0.2"

[dev-dependencies]
criterion = "^0.2"

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "canonicalize"
harness = false
