[package]
name = "unic-locale"
description = "API for managing Unicode Locale Identifiers"
version = "0.5.2"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zbraniecki/unic-locale"
license = "MIT/Apache-2.0"
categories = ["internationalization"]

[dependencies]
unic-langid-impl = "0.5.2"
unic-locale-impl = "0.5.2"
unic-locale-macros = { version = "0.5", optional = true }

[dev-dependencies]
unic-locale-macros = "0.5"

[features]
default = []

# Provide macros.
macros = ["unic-locale-macros"]
likelysubtags = ["unic-locale-impl/likelysubtags"]
