[package]
name = "unic-locale"
description = "API for managing Unicode Locale Identifiers"
version = "0.7.1"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zbraniecki/unic-locale"
license = "MIT/Apache-2.0"
categories = ["internationalization"]

[dependencies]
unic-langid-impl = { path = "../unic-langid-impl" }
unic-locale-impl = { path = "../unic-locale-impl" }
unic-locale-macros = { version = "0.7" , optional = true }

[dev-dependencies]
unic-locale-macros = "0.7"

[features]
default = []

# Provide macros.
macros = ["unic-locale-macros"]
likelysubtags-inline = ["unic-locale-impl/likelysubtags-inline"]
likelysubtags-cldr = ["unic-locale-impl/likelysubtags-cldr"]
